In [8]:
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import ascii
import pandas as pd

In [9]:
from astropy.table import Table
t = Table.read("bsc5.dat", format = "ascii.tab")

#
#print(t[0][0][103])


(9109,)


In [7]:
data = ascii.read("bsc5.dat", guess = False, fast_reader = False, format = "tab") 
#print(data)


In [24]:
# 103-107  F5.2   mag     Vmag     Visual magnitude (1)
# 162-166  F5.3   arcsec  Parallax ? Trigonometric parallax (unless n_Parallax)
m1 = data[1][0][103] #Se cambia el primer numero para cambiar la fila
m2 = data[1][0][104]
m3 = data[1][0][105]
m4 = data[1][0][106]
p = float(m1+m2+m3+m4)
print(p)
p?

4.61


In [13]:
np.isfinite?

In [101]:
a = np.zeros([8,4])
out = []
#print(a, "\n")

for i in range(len(a)):
    for j in range(len(a[0])):
        a[i,j]=i*j
print(a, "\n")
print(len(a),len(a[0]))
print(a[5][2])

for i in range(len(a)):
     out.append(i)
print(out)
#for i in a:
#    out.append([i])

#print(out)




[[ 0.  0.  0.  0.]
 [ 0.  1.  2.  3.]
 [ 0.  2.  4.  6.]
 [ 0.  3.  6.  9.]
 [ 0.  4.  8. 12.]
 [ 0.  5. 10. 15.]
 [ 0.  6. 12. 18.]
 [ 0.  7. 14. 21.]] 

8 4
10.0
[0, 1, 2, 3, 4, 5, 6, 7]
